name: wordle
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+5
  flutter_animate: ^4.1.1+1
  mobx: ^2.2.0
  animated_snack_bar: ^0.3.1
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: BalooChettan2
      fonts:
        - asset: assets/fonts/BalooChettan2-Regular.ttf
        - asset: assets/fonts/BalooChettan2-Medium.ttf
        - asset: assets/fonts/BalooChettan2-SemiBold.ttf
        - asset: assets/fonts/BalooChettan2-Bold.ttf
        - asset: assets/fonts/BalooChettan2-eXTRABold.ttf
